### WARNING:
#   remember to edit Configuration.py and enable the corresponding set of variables

cd ../MyDNNKit/

python RunML.py --LoadTrainedModel --doConfusionMatrix --doScore --doEfficiency --doROC  --massPointToTest [400] --inSignalFiles=ggFH400 --inDataFiles data --inBackgrFiles top,diboson,Wjets,Zjets --PDPath /nfs/kloe/einstein2/enricojr/data/2019-11-04/pandas_resolved_ggF/ --MixPD_TrainTestTag mixPD_resolved_ggF  --TrainedModelPath /nfs/kloe/einstein2/enricojr/data/2019-11-04/pandas_resolved_ggF/train_2variables/llqqDNN_64_1024_4_0.0003_VarSet0/ -o /nfs/kloe/einstein2/enricojr/data/2019-11-04/pandas_resolved_ggF/test_2variables/ -m binary

python RunML.py --LoadTrainedModel --doConfusionMatrix --doScore --doEfficiency --doROC  --massPointToTest [400] --inSignalFiles=ggFH400 --inDataFiles data --inBackgrFiles top,diboson,Wjets,Zjets --PDPath /nfs/kloe/einstein2/enricojr/data/2019-11-04/pandas_resolved_ggF/ --MixPD_TrainTestTag mixPD_resolved_ggF  --TrainedModelPath /nfs/kloe/einstein2/enricojr/data/2019-11-04/pandas_resolved_ggF/train_2variables/llqqDNN_64_1024_4_0.0003_VarSet1/ -o /nfs/kloe/einstein2/enricojr/data/2019-11-04/pandas_resolved_ggF/test_2variables/ -m binary

python RunML.py --LoadTrainedModel --doConfusionMatrix --doScore --doEfficiency --doROC  --massPointToTest [400] --inSignalFiles=ggFH400 --inDataFiles data --inBackgrFiles top,diboson,Wjets,Zjets --PDPath /nfs/kloe/einstein2/enricojr/data/2019-11-04/pandas_resolved_ggF/ --MixPD_TrainTestTag mixPD_resolved_ggF  --TrainedModelPath /nfs/kloe/einstein2/enricojr/data/2019-11-04/pandas_resolved_ggF/train_2variables/llqqDNN_64_1024_4_0.0003_VarSet2/ -o /nfs/kloe/einstein2/enricojr/data/2019-11-04/pandas_resolved_ggF/test_2variables/ -m binary

python RunML.py --LoadTrainedModel --doConfusionMatrix --doScore --doEfficiency --doROC  --massPointToTest [400] --inSignalFiles=ggFH400 --inDataFiles data --inBackgrFiles top,diboson,Wjets,Zjets --PDPath /nfs/kloe/einstein2/enricojr/data/2019-11-04/pandas_resolved_ggF/ --MixPD_TrainTestTag mixPD_resolved_ggF  --TrainedModelPath /nfs/kloe/einstein2/enricojr/data/2019-11-04/pandas_resolved_ggF/train_2variables/llqqDNN_64_1024_4_0.0003_VarSet3/ -o /nfs/kloe/einstein2/enricojr/data/2019-11-04/pandas_resolved_ggF/test_2variables/ -m binary

python RunML.py --LoadTrainedModel --doConfusionMatrix --doScore --doEfficiency --doROC  --massPointToTest [400] --inSignalFiles=ggFH400 --inDataFiles data --inBackgrFiles top,diboson,Wjets,Zjets --PDPath /nfs/kloe/einstein2/enricojr/data/2019-11-04/pandas_resolved_ggF/ --MixPD_TrainTestTag mixPD_resolved_ggF  --TrainedModelPath /nfs/kloe/einstein2/enricojr/data/2019-11-04/pandas_resolved_ggF/train_2variables/llqqDNN_64_1024_4_0.0003_VarSet4/ -o /nfs/kloe/einstein2/enricojr/data/2019-11-04/pandas_resolved_ggF/test_2variables/ -m binary

python RunML.py --LoadTrainedModel --doConfusionMatrix --doScore --doEfficiency --doROC  --massPointToTest [400] --inSignalFiles=ggFH400 --inDataFiles data --inBackgrFiles top,diboson,Wjets,Zjets --PDPath /nfs/kloe/einstein2/enricojr/data/2019-11-04/pandas_resolved_ggF/ --MixPD_TrainTestTag mixPD_resolved_ggF  --TrainedModelPath /nfs/kloe/einstein2/enricojr/data/2019-11-04/pandas_resolved_ggF/train_2variables/llqqDNN_64_1024_4_0.0003_VarSet5/ -o /nfs/kloe/einstein2/enricojr/data/2019-11-04/pandas_resolved_ggF/test_2variables/ -m binary

python RunML.py --LoadTrainedModel --doConfusionMatrix --doScore --doEfficiency --doROC  --massPointToTest [400] --inSignalFiles=ggFH400 --inDataFiles data --inBackgrFiles top,diboson,Wjets,Zjets --PDPath /nfs/kloe/einstein2/enricojr/data/2019-11-04/pandas_resolved_ggF/ --MixPD_TrainTestTag mixPD_resolved_ggF  --TrainedModelPath /nfs/kloe/einstein2/enricojr/data/2019-11-04/pandas_resolved_ggF/train_2variables/llqqDNN_64_1024_4_0.0003_VarSet6/ -o /nfs/kloe/einstein2/enricojr/data/2019-11-04/pandas_resolved_ggF/test_2variables/ -m binary


python RunML.py --LoadTrainedModel --doConfusionMatrix --doScore --doEfficiency --doROC  --massPointToTest [700] --inSignalFiles=VBFH700 --inDataFiles data --inBackgrFiles top,diboson,Wjets,Zjets --PDPath /nfs/kloe/einstein2/enricojr/data/2019-11-04/pandas_resolved_VBF/ --MixPD_TrainTestTag mixPD_resolved_VBF  --TrainedModelPath /nfs/kloe/einstein2/enricojr/data/2019-11-04/pandas_resolved_VBF/train_2variables/llqqDNN_64_1024_4_0.0003_VarSet0/ -o /nfs/kloe/einstein2/enricojr/data/2019-11-04/pandas_resolved_VBF/test_2variables/ -m binary

python RunML.py --LoadTrainedModel --doConfusionMatrix --doScore --doEfficiency --doROC  --massPointToTest [700] --inSignalFiles=VBFH700 --inDataFiles data --inBackgrFiles top,diboson,Wjets,Zjets --PDPath /nfs/kloe/einstein2/enricojr/data/2019-11-04/pandas_resolved_VBF/ --MixPD_TrainTestTag mixPD_resolved_VBF  --TrainedModelPath /nfs/kloe/einstein2/enricojr/data/2019-11-04/pandas_resolved_VBF/train_2variables/llqqDNN_64_1024_4_0.0003_VarSet1/ -o /nfs/kloe/einstein2/enricojr/data/2019-11-04/pandas_resolved_VBF/test_2variables/ -m binary

python RunML.py --LoadTrainedModel --doConfusionMatrix --doScore --doEfficiency --doROC  --massPointToTest [700] --inSignalFiles=VBFH700 --inDataFiles data --inBackgrFiles top,diboson,Wjets,Zjets --PDPath /nfs/kloe/einstein2/enricojr/data/2019-11-04/pandas_resolved_VBF/ --MixPD_TrainTestTag mixPD_resolved_VBF  --TrainedModelPath /nfs/kloe/einstein2/enricojr/data/2019-11-04/pandas_resolved_VBF/train_2variables/llqqDNN_64_1024_4_0.0003_VarSet2/ -o /nfs/kloe/einstein2/enricojr/data/2019-11-04/pandas_resolved_VBF/test_2variables/ -m binary

python RunML.py --LoadTrainedModel --doConfusionMatrix --doScore --doEfficiency --doROC  --massPointToTest [700] --inSignalFiles=VBFH700 --inDataFiles data --inBackgrFiles top,diboson,Wjets,Zjets --PDPath /nfs/kloe/einstein2/enricojr/data/2019-11-04/pandas_resolved_VBF/ --MixPD_TrainTestTag mixPD_resolved_VBF  --TrainedModelPath /nfs/kloe/einstein2/enricojr/data/2019-11-04/pandas_resolved_VBF/train_2variables/llqqDNN_64_1024_4_0.0003_VarSet3/ -o /nfs/kloe/einstein2/enricojr/data/2019-11-04/pandas_resolved_VBF/test_2variables/ -m binary

python RunML.py --LoadTrainedModel --doConfusionMatrix --doScore --doEfficiency --doROC  --massPointToTest [700] --inSignalFiles=VBFH700 --inDataFiles data --inBackgrFiles top,diboson,Wjets,Zjets --PDPath /nfs/kloe/einstein2/enricojr/data/2019-11-04/pandas_resolved_VBF/ --MixPD_TrainTestTag mixPD_resolved_VBF  --TrainedModelPath /nfs/kloe/einstein2/enricojr/data/2019-11-04/pandas_resolved_VBF/train_2variables/llqqDNN_64_1024_4_0.0003_VarSet4/ -o /nfs/kloe/einstein2/enricojr/data/2019-11-04/pandas_resolved_VBF/test_2variables/ -m binary

python RunML.py --LoadTrainedModel --doConfusionMatrix --doScore --doEfficiency --doROC  --massPointToTest [700] --inSignalFiles=VBFH700 --inDataFiles data --inBackgrFiles top,diboson,Wjets,Zjets --PDPath /nfs/kloe/einstein2/enricojr/data/2019-11-04/pandas_resolved_VBF/ --MixPD_TrainTestTag mixPD_resolved_VBF  --TrainedModelPath /nfs/kloe/einstein2/enricojr/data/2019-11-04/pandas_resolved_VBF/train_2variables/llqqDNN_64_1024_4_0.0003_VarSet5/ -o /nfs/kloe/einstein2/enricojr/data/2019-11-04/pandas_resolved_VBF/test_2variables/ -m binary

python RunML.py --LoadTrainedModel --doConfusionMatrix --doScore --doEfficiency --doROC  --massPointToTest [700] --inSignalFiles=VBFH700 --inDataFiles data --inBackgrFiles top,diboson,Wjets,Zjets --PDPath /nfs/kloe/einstein2/enricojr/data/2019-11-04/pandas_resolved_VBF/ --MixPD_TrainTestTag mixPD_resolved_VBF  --TrainedModelPath /nfs/kloe/einstein2/enricojr/data/2019-11-04/pandas_resolved_VBF/train_2variables/llqqDNN_64_1024_4_0.0003_VarSet6/ -o /nfs/kloe/einstein2/enricojr/data/2019-11-04/pandas_resolved_VBF/test_2variables/ -m binary

cd -
